### ISSUE TITLE
Mobile drag issues

### ISSUE THREAD

**Issue by NyarukoDev** [CaptainCodeman/svelte-image-comparison#1]
Hi, trying to use this for a responsive site but the mobile control of the slider is a bit iffy. The images open a context menu while trying to drag and the drag line itself doesn't follow the tap very far. The latter part can be replicated using developer tool's device toolbar but image context menu I only found on actual mobile.

Cheers

**Comment by CaptainCodeman** [comment]
Let me know if that doesn't fix it.
